import React, { useEffect, useState } from 'react';
import { Modal } from '../common/Modal';
import { useApp } from '../../context/AppContext';
import { useAuth } from '../../context/AuthContext';
import { Plus, Save } from 'lucide-react';
import { Campaign } from '../../types';

interface CreateCampaignModalProps { isOpen: boolean; onClose: () => void; campaign?: Campaign | null; }
type CampaignPlatform = 'instagram' | 'youtube';
const empty = { title:'', description:'', category:'Tech & Gadgets', budget:5000, minFollowers:10000, deadline:'2026-09-30', targetPlatforms:['instagram','youtube'] as CampaignPlatform[] };

export const CreateCampaignModal: React.FC<CreateCampaignModalProps> = ({ isOpen, onClose, campaign }) => {
  const { createCampaign, updateCampaign, addToast } = useApp(); const { user } = useAuth(); const [form,setForm] = useState(empty);
  useEffect(() => { setForm(campaign ? { title:campaign.title, description:campaign.description, category:campaign.category, budget:campaign.budget, minFollowers:campaign.minFollowers, deadline:campaign.deadline, targetPlatforms:campaign.targetPlatforms.filter((p): p is CampaignPlatform => p === 'instagram' || p === 'youtube') } : empty); }, [campaign, isOpen]);
  const toggle = (platform: CampaignPlatform) => setForm(prev => ({...prev,targetPlatforms:prev.targetPlatforms.includes(platform) ? prev.targetPlatforms.filter(x=>x!==platform) : [...prev.targetPlatforms,platform]}));
  const submit = (status: Campaign['status']) => {
    if (!form.title.trim() || !form.description.trim()) { addToast('error','Add a title and campaign description'); return; }
    if (!form.targetPlatforms.length) { addToast('error','Select at least one platform'); return; }
    const payload = {...form, targetPlatforms:form.targetPlatforms, requirements:form.targetPlatforms.map(platform => ({platform,contentType:platform === 'instagram' ? 'Reels / Posts' : 'Dedicated video',quantity:1})), status};
    if (campaign) updateCampaign(campaign.id, payload); else createCampaign({brandId:user?.id || 'brand-1',brandName:(user as any)?.companyName || 'Indus Tech Innovations',brandLogo:(user as any)?.logo || '',...payload});
    addToast('success', status === 'draft' ? 'Campaign saved as draft' : campaign ? 'Campaign updated' : 'Campaign published'); onClose();
  };
  const text='w-full text-xs bg-slate-50 border border-slate-200 rounded-xl p-3 text-slate-800 focus:outline-none focus:ring-2 focus:ring-pink-500';
  return <Modal isOpen={isOpen} onClose={onClose} title={campaign ? 'Edit Campaign' : 'Create New Collaboration Campaign'}><form onSubmit={e=>{e.preventDefault();submit('active')}} className="space-y-4"><label className="block text-xs font-semibold text-slate-700">Campaign Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Summer Product Launch 2026" className={`${text} mt-1`} required/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-700">Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className={`${text} mt-1`}>{['Tech & Gadgets','Fashion & Lifestyle','Fitness & Wellness','Gaming','Travel','Beauty & Skincare'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-semibold text-slate-700">Total Budget (₹)<input type="number" min="1" value={form.budget} onChange={e=>setForm({...form,budget:Number(e.target.value)})} className={`${text} mt-1`} required/></label></div><label className="block text-xs font-semibold text-slate-700">Campaign Description & Goals<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className={`${text} mt-1`} required/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-700">Minimum Followers<input type="number" min="0" value={form.minFollowers} onChange={e=>setForm({...form,minFollowers:Number(e.target.value)})} className={`${text} mt-1`}/></label><label className="text-xs font-semibold text-slate-700">Submission Deadline<input type="date" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})} className={`${text} mt-1`}/></label></div><div><p className="text-xs font-semibold text-slate-700 mb-2">Target Platforms</p><div className="flex gap-2">{(['instagram','youtube'] as const).map(platform=><button key={platform} type="button" onClick={()=>toggle(platform)} className={`px-3 py-1.5 rounded-xl text-xs font-semibold border capitalize transition-all hover:-translate-y-0.5 ${form.targetPlatforms.includes(platform)?'bg-[#EC4899] text-white border-[#EC4899]':'bg-slate-50 text-slate-600 border-slate-200'}`}>{platform}</button>)}</div></div><div className="flex justify-end gap-2 pt-3 border-t"><button type="button" onClick={onClose} className="px-4 py-2 text-xs font-medium text-slate-600 hover:bg-slate-100 rounded-xl">Cancel</button>{!campaign && <button type="button" onClick={()=>submit('draft')} className="px-4 py-2 border border-slate-200 text-slate-700 hover:bg-slate-50 font-bold text-xs rounded-xl flex gap-1.5"><Save className="w-3.5 h-3.5"/>Save as Draft</button>}<button type="submit" className="px-5 py-2.5 bg-[#EC4899] hover:bg-pink-600 text-white font-semibold text-xs rounded-xl transition-all shadow-md flex gap-2"><Plus className="w-4 h-4"/>{campaign ? 'Save Changes' : 'Publish Campaign'}</button></div></form></Modal>;
};
