import React, { useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext';
import { useApp } from '../../context/AppContext';
import { Card } from '../../components/common/Card';
import { EmptyState } from '../../components/common/EmptyState';
import { Skeleton } from '../../components/common/Skeleton';
import { AlertCircle, MessageSquare, Star } from 'lucide-react';

const Stars: React.FC<{ rating:number }> = ({rating}) => <span className="flex text-amber-400">{[1,2,3,4,5].map(x=><Star key={x} className={`w-3.5 h-3.5 ${x<=rating?'fill-amber-400':''}`}/>)}</span>;

export const CreatorReviews: React.FC = () => {
 const { user } = useAuth(); const { creators } = useApp(); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const creator = creators.find(c=>c.id===user?.id) || creators[0];
 useEffect(()=>{const timer=window.setTimeout(()=>setLoading(false),250);return()=>window.clearTimeout(timer)},[]);
 if (loading) return <div className="space-y-6 max-w-4xl"><Skeleton className="h-9 w-64"/><Skeleton className="h-36 w-full rounded-3xl"/><Skeleton className="h-40 w-full"/></div>;
 if (error || !creator) return <EmptyState icon={AlertCircle} title="Reviews could not be loaded" description={error || 'Please refresh and try again.'} actionLabel="Try again" onAction={()=>setError('')}/>;
 const reviews=creator.reviews; const total=reviews.length; const average=total ? reviews.reduce((sum,r)=>sum+r.rating,0)/total : 0; const distribution=[5,4,3,2,1].map(rating=>({rating,count:reviews.filter(r=>r.rating===rating).length}));
 return <div className="space-y-6 max-w-4xl"><div><h1 className="text-2xl font-black text-slate-900 tracking-tight">Client Reviews & Testimonials</h1><p className="text-xs text-slate-500">Verified feedback from completed brand collaborations.</p></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Card className="md:col-span-1 p-6 bg-slate-900 text-white"><p className="text-xs text-slate-300">Average rating</p><div className="flex items-end gap-2 mt-2"><span className="text-4xl font-black text-amber-400">{average.toFixed(1)}</span><Stars rating={Math.round(average)}/></div><p className="text-[10px] text-slate-400 mt-2">Based on {total} total reviews</p></Card><Card className="md:col-span-2 p-5"><h2 className="text-xs font-bold text-slate-800 mb-4">Rating distribution</h2><div className="space-y-2.5">{distribution.map(({rating,count})=><div key={rating} className="flex items-center gap-3 text-[11px]"><span className="w-10 flex items-center gap-1 font-bold text-slate-600">{rating}<Star className="w-3 h-3 fill-amber-400 text-amber-400"/></span><div className="h-2 flex-1 rounded-full bg-slate-100 overflow-hidden"><div className="h-full rounded-full bg-amber-400 transition-all" style={{width:`${total?count/total*100:0}%`}}/></div><span className="w-6 text-right text-slate-400">{count}</span></div>)}</div></Card></div><div className="space-y-4">{reviews.length===0?<EmptyState icon={MessageSquare} title="No reviews yet" description="Reviews from completed collaborations will appear here."/>:reviews.map(review=><Card key={review.id} className="p-5 border-slate-200/90 space-y-3"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><img src={review.reviewerAvatar} alt={`${review.reviewerName} logo`} className="w-10 h-10 rounded-xl object-cover border border-slate-200"/><div><h2 className="text-sm font-bold text-slate-900">{review.reviewerName}</h2><p className="text-[10px] text-slate-400">{review.date}{review.campaignTitle ? ` · ${review.campaignTitle}` : ''}</p></div></div><div className="text-right"><Stars rating={review.rating}/><p className="text-[10px] font-bold text-amber-600 mt-1">{review.rating}.0 / 5</p></div></div><p className="text-xs text-slate-600 leading-relaxed bg-slate-50 p-3 rounded-xl border border-slate-100">“{review.comment}”</p></Card>)}</div></div>;
};
